### ISSUE TITLE
Error when one parser inherits from other 

### ISSUE THREAD

**Issue by arikon** [veged/ometa-js#11]
```
TypeError: object is not a function
    at Function.matchAll (/Users/arikon/projects/bem/borschik/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:43:14)
    at Function.match (/Users/arikon/projects/bem/borschik/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:30:15)
    at Function.BorschikCSSChilds.childs (/Users/arikon/projects/bem/borschik/lib/techs/css.ometajs.js:14:17)
    at exports.Tech.INHERIT.File.INHERIT.parseInclude (/Users/arikon/projects/bem/borschik/lib/techs/css.js:17:33)
    at exports.Tech.INHERIT.File.exports.File.INHERIT.parse (/Users/arikon/projects/bem/borschik/lib/tech.js:36:26)
    at exports.Tech.INHERIT.File.exports.File.INHERIT.read (/Users/arikon/projects/bem/borschik/lib/tech.js:26:37)
    at Cmd.<anonymous> (/Users/arikon/projects/bem/borschik/lib/borschik.js:40:18)
    at exports.Cmd.Cmd._do (/Users/arikon/projects/bem/borschik/node_modules/coa/lib/cmd.js:427:22)
    at _fulfilled (/Users/arikon/projects/bem/borschik/node_modules/coa/node_modules/q/q.js:934:32)
    at resolvedValue.promiseSend.done (/Users/arikon/projects/bem/borschik/node_modules/coa/node_modules/q/q.js:956:30)
```

**Comment by indutny** [comment]
I think this may happen if you're trying to inherit old grammar from a new one, is this your case?

**Comment by arikon** [comment]
@indutny You can reproduce it by running `borschik` from `master`: https://github.com/veged/borschik
Try to run `borschik -t css -i any.css`. You can use any css file, empty one will also work (do not work in this case ;)

**Comment by arikon** [comment]
@indutny ping?

**Comment by indutny** [comment]
@arikon found source of the problem, fixed in #36

**Comment by arikon** [comment]
veged/borschik#36

**Comment by arikon** [comment]
Fixed in `borschik`.

@indutny Thanks!
