### ISSUE TITLE
"Unexpected token: punc (:)" error when returning object literal

### ISSUE THREAD

**Issue by emertechie** [veged/ometa-js#22]
When I try to use a grammar like the following (that returns an object literal)

```
ometa Lisp {
  // Lexer
  identifier = <letter+>:id      -> { type: "Id", value: id },
  number     = <digit+>:num      -> { type: "Number", value: parseInt(num) },
  punctuator = '(' | ')' |'.' | ',',

  token :tt  = spaces ( punctuator:t             ?(t == tt)      -> t
                      | (identifier | number):t  ?(t.type == tt) -> t
                      ),

  // Parser
  list       = token("(") (atom | list)+:cs token(")") -> { type: "List", content: cs },
  atom       = token("Id") | token("Number")
}
```

I get the error:

```
Unexpected token: punc (:) (line: 2, col: 9, pos: 22)

Error
at new JS_Parse_Error (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:263:18)
at js_error (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:271:11)
at croak (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:733:9)
at token_error (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:740:9)
at unexpected (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:746:9)
at Object.semicolon [as 1] (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:766:43)
at prog1 (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:1314:21)
at simple_statement (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:906:27)
at C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:801:47
at block_ (C:\Source\Tests\OMeta\node_modules\ometajs\node_modules\uglify-js\lib\parse-js.js:1003:20)
```

However if I call a function with that literal, then it works so I'm hacking around it for now like this:

```
function obj(o) { return o; }

ometa Lisp {
  // Lexer
  identifier = <letter+>:id      -> obj({ type: "Id", value: id }),
  number     = <digit+>:num      -> obj({ type: "Number", value: parseInt(num) }),
  punctuator = '(' | ')' |'.' | ',',

  token :tt  = spaces ( punctuator:t             ?(t == tt)      -> t
                      | (identifier | number):t  ?(t.type == tt) -> t
                      ),

  // Parser
  list       = token("(") (atom | list)+:cs token(")") -> obj({ type: "List", content: cs }),
  atom       = token("Id") | token("Number")
}
```

On a Windows box btw

**Comment by indutny** [comment]
Well, it might be not quite convenient, but doing `rule -> ({ json: true })` should work just fine. The thing is that javascript allows labels in code, thus: `rule -> { json: true }` could be read as:

```
{
  json: // this is a label, not a property name
  true
}
```
